### PR TITLE
update example data

### PR DESCRIPTION
**Pull request by ngreenwald**
Removes the old example data and adds new data that follows the raw data ontology.

@epao111, I have the wrong metadata file in the A549 folder as a placeholder. Could you send me the right one for the 3D and 2D data?

### CODE REVIEW

**Comment by ngreenwald** [comment]
Okay, I updated the 2D metadata with the correct metadata file from Ed. We have a placeholder metadata file for the 3D data while Ed is figuring out how to properly represent stacked data. 

@MekWarrior, your call if you want to merge with the placeholder or wait until you and Ed hash our the 3D metadata file.

**Comment by ngreenwald** [comment]
Alright, added the new metadata file

**Comment by MekWarrior** [comment]
@willgraf is it worth adapting some of the keras-style download functions to this repo for the data? There's two points to the data being here: one is for test/training purposes and the other is to illustrate the ontology we expect. Perhaps we should even state that ontology expressly in the readme?

**Comment by MekWarrior** [comment]
Further work needed to close #57, but it looks good to pull this in.

**Pull request merged**
