### PR TITLE
Save compressed NPZs

### PR DESCRIPTION
**Pull request by ngreenwald**
This PR switches the default from np.savez() to np.savez_compressed() to reduce file size. It also passes in the dtype parameter from the input data to all of the crops to allow specification of a smaller dtype to be propagated throughout the pipeline.

### CODE REVIEW

**Comment by ngreenwald** [comment]
Nope, no particular reason. We can switch to uint16 for those functions. I was also thinking about where the best place would be for dtype downsizing. e.g. data gets read in as int32/64, but the max is much lower than that and doesn't require the large file size. 

Would running it through some sort of checking function to see if downsizing is possible be useful?

**Comment by geneva-miller** [comment]
I'm curious to hear what you have in mind for a checking function. Are we just talking about reading labels for dtype downsizing? If it's just labels, I'm inclined to downsize by default--I think it's fair to assume that caliban use cases (especially browser) won't ever need a larger dtype.

**Comment by ngreenwald** [comment]
This would be for labels and image data. So you'd need to divide by the max
if you have data that goes about 32k.
I'm not sure if that would interfere with any of the transforms you apply
to the data? The other issue is that the smallest dtype, float16, can't be
visualized with most of the default plotting stuff.

**Comment by geneva-miller** [comment]
Gotcha. I'm reluctant to mess with the dtype of `X` data right now, but I can imagine doing something like that near the end of the image processing steps to make a smaller npz. So I think we should revisit image dtype changes later, but I don't see any problems with changing the label dtype now.

**Comment by ngreenwald** [comment]
Okay cool, was there anywhere else that default was set? I changed the one I saw.

**Comment by geneva-miller** [comment]
No, I think the only other way we get labels in would be via prediction (or loading predicted labels) and those aren't really handled by the current utils (I think).

**Pull request merged**
